{
 "title": "Data MQ135 Sensor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Rzero PPM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_rzero\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mq135_rzero\")"
    }
   ]
  },
  {
   "title": "Rzero PPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_rzero\")"
    }
   ]
  },
  {
   "title": "Correct Rzero 1 PPM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_corrected_rzero_1\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mq135_corrected_rzero_1\")"
    }
   ]
  },
  {
   "title": "Correct RZero 1 PPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_corrected_rzero_1\")"
    }
   ]
  },
  {
   "title": "Correct Rzero 2 PPM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_corrected_rzero_2\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mq135_corrected_rzero_2\")"
    }
   ]
  },
  {
   "title": "Correct Rzero 2 PPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_corrected_rzero_2\")"
    }
   ]
  },
  {
   "title": "Resistance PPM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_resistance\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mq135_resistance\")"
    }
   ]
  },
  {
   "title": "Resistance PPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_resistance\")"
    }
   ]
  },
  {
   "title": "PPM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_ppm\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mq135_ppm\")"
    }
   ]
  },
  {
   "title": "PPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_ppm\")"
    }
   ]
  },
  {
   "title": "Correct 1 PPM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_corrected_ppm_1\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mq135_corrected_ppm_1\")"
    }
   ]
  },
  {
   "title": "Correct 1 PPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_corrected_ppm_1\")"
    }
   ]
  },
  {
   "title": "Correct 2 PPM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_corrected_ppm_2\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mq135_corrected_ppm_2\")"
    }
   ]
  },
  {
   "title": "Correct 2 PPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mq135_corrected_ppm_2\")"
    }
   ]
  }
 ]
}