{
 "title": "Data DHT22 Sensor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Temperature Sensor 1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor1_temperature\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"temperature1\")"
    }
   ]
  },
  {
   "title": "Temperature Sensor 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor1_temperature\")"
    }
   ]
  },
  {
   "title": "Humidity Sensor 1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor1_humidity\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"humidity1\")"
    }
   ]
  },
  {
   "title": "Humidity Sensor 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor1_humidity\")"
    }
   ]
  },
  {
   "title": "Temperature Sensor 2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor2_temperature\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"temperature2\")"
    }
   ]
  },
  {
   "title": "Temperature Sensor 2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor2_temperature\")"
    }
   ]
  },
  {
   "title": "Humidity Sensor 2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor2_humidity\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"humidity2\")"
    }
   ]
  },
  {
   "title": "Humidity Sensor 2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"Sensor\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor2_humidity\")"
    }
   ]
  }
 ]
}