version: "3.8"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    networks:
      - server_network

  grafana:
    image: grafana/grafana:main
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
    networks:
      - server_network
    depends_on:
      - influxdb

  telegraf_sensor:
    image: telegraf:latest
    container_name: telegraf_sensor
    restart: always
    volumes:
      - telegraf_config:/etc/telegraf    # Direktori konfigurasi telegraf
    networks:
      - server_network
    depends_on:
      - influxdb 

  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - "8040:443"   # Nextcloud akan berjalan di port 8040 (https)
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - nextcloud_data:/config
      - nextcloud_html:/data
    networks:
      - server_network

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: always
    network_mode: host
    volumes:
      - homeassistant_data:/config
    environment:
      - TZ=Asia/Jakarta

networks:
  server_network:  # 🔹 Jaringan khusus untuk semua container
    driver: bridge

volumes:
  influxdb_data:
    driver: local
  influxdb_config:
    driver: local
  grafana_data:
    driver: local
  grafana_config:
    driver: local
  telegraf_config:
    driver: local
  nextcloud_data:
    driver: local
  nextcloud_html:
    driver: local
  homeassistant_data:
    driver: local
